import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { api } from '../api';
import { useAuth } from '../context/AuthContext';
import '../pages/Dashboard.css';

function escapeCsv(val) {
  if (val == null) return '';
  const str = String(val);
  if (str.includes(',') || str.includes('"') || str.includes('\n')) {
    return '"' + str.replace(/"/g, '""') + '"';
  }
  return str;
}

function downloadCsv(filename, rows) {
  const csv = rows.map(row => row.map(escapeCsv).join(',')).join('\n');
  const blob = new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export default function QuizResults() {
  const { classId, quizId } = useParams();
  const { token } = useAuth();
  const navigate = useNavigate();
  const [results, setResults] = useState([]);
  const [error, setError] = useState('');
  const [downloading, setDownloading] = useState(null);

  useEffect(() => {
    api.get(`/classes/${classId}/quizzes/${quizId}/results`, token)
      .then(setResults)
      .catch(e => setError(e.message));
  }, []);

  async function handleDownload(attemptId, studentName) {
    setDownloading(attemptId);
    try {
      const data = await api.get(
        `/classes/${classId}/quizzes/${quizId}/attempts/${attemptId}/detail`,
        token
      );
      const percentage = Math.round((data.score / data.total) * 100);
      const date = new Date(data.attempted_at).toLocaleString();
      const grade = percentage >= 90 ? 'A' : percentage >= 80 ? 'B' : percentage >= 70 ? 'C' : percentage >= 60 ? 'D' : 'F';

      const rows = [
        // Branding header
        ['Student.umunsi.com', '', '', '', ''],
        ['Official Quiz Result Report', '', '', '', ''],
        [],
        // Institution / context info
        ['School',        data.school_name],
        ['Class',         data.class_name],
        ['Subject',       data.class_subject || 'N/A'],
        ['Teacher',       data.teacher_name],
        ['Quiz #',        data.quiz_number],
        ['Quiz Title',    data.quiz_title],
        [],
        // Student result summary
        ['Student Name',  data.student_name],
        ['Score',         `${data.score} / ${data.total}`],
        ['Percentage',    `${percentage}%`],
        ['Grade',         grade],
        ['Date Taken',    date],
        [],
        // Separator line before questions
        ['='.repeat(30),'','','',''],
        ['#', 'Question', 'Student Answer', 'Correct Answer', 'Result'],
        ...data.questions.map(q => [
          q.number,
          q.question,
          `${q.student_answer.toUpperCase()}: ${q.student_answer_text}`,
          `${q.correct_answer.toUpperCase()}: ${q.correct_answer_text}`,
          q.is_correct ? '✓ Correct' : '✗ Wrong',
        ]),
        [],
        ['Generated by Student.umunsi.com', '', '', '', new Date().toLocaleString()],
      ];
      const safeName = studentName.replace(/[^a-z0-9]/gi, '_');
      downloadCsv(`${data.quiz_title}_${safeName}.csv`, rows);
    } catch (e) {
      setError(e.message);
    } finally {
      setDownloading(null);
    }
  }

  return (
    <div className="class-page">
      <header className="dash-header">
        <button className="btn btn-outline btn-sm" onClick={() => navigate(-1)}>← Back</button>
        <div className="dash-brand">🎓 UClass</div>
      </header>
      <main className="class-main">
        <h2 style={{ marginBottom: 24 }}>Quiz Results</h2>
        {error && <div className="alert alert-error">{error}</div>}
        <div className="students-table">
          <table>
            <thead>
              <tr>
                <th>Rank</th>
                <th>Student</th>
                <th>Score</th>
                <th>Percentage</th>
                <th>Date</th>
                <th>Download</th>
              </tr>
            </thead>
            <tbody>
              {results.map((r, i) => (
                <tr key={r.id}>
                  <td>{i + 1}</td>
                  <td>{r.student_name}</td>
                  <td><strong>{r.score}/{r.total}</strong></td>
                  <td>{Math.round((r.score / r.total) * 100)}%</td>
                  <td>{new Date(r.attempted_at).toLocaleDateString()}</td>
                  <td>
                    <button
                      className="btn btn-outline btn-sm"
                      onClick={() => handleDownload(r.id, r.student_name)}
                      disabled={downloading === r.id}
                    >
                      {downloading === r.id ? 'Downloading…' : '⬇ CSV'}
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          {results.length === 0 && <p style={{ padding: 20, textAlign: 'center', color: '#888' }}>No attempts yet.</p>}
        </div>
      </main>
    </div>
  );
}
